---
- name: "PLAY 1: SETUP DEVICES WITHIN NETBOX"
  hosts: localhost
  connection: local
  vars:
    install_state: present
  tasks:
    - name: "TASK 0: SETUP SITES"
      debug:
              msg: "'{{ lookup('env', 'NETBOX_URL') }}' is the URL environment variable."

    - name: "TASK 1: SETUP SITES"
      netbox.netbox.netbox_site:
        netbox_url: "{{ lookup('env', 'NETBOX_URL') }}"
        netbox_token: "{{ lookup('env', 'NETBOX_API_KEY') }}"
        validate_certs: no
        data: "{{ site }}"
        state: "{{ install_state }}"
      register: site_setup
      loop: "{{ sites }}"
      loop_control:
        loop_var: site
        label: "{{ site['name'] }}"
      tags: [ sites, devices ]


    - name: "TASK 2: SETUP RACKS"
      netbox.netbox.netbox_rack:
        netbox_url: "{{ lookup('env', 'NETBOX_URL') }}"
        netbox_token: "{{ lookup('env', 'NETBOX_API_KEY') }}"
        data: "{{ rack }}"
        state: "{{ install_state }}"
      loop: "{{ racks }}"
      loop_control:
        loop_var: rack
        label: "{{ rack['name'] }}"
      tags: [ sites, devices ]

    - name: "TASK 3: SETUP MANUFACTURERS"
      netbox.netbox.netbox_manufacturer:
        netbox_url: "{{ lookup('env', 'NETBOX_URL') }}"
        netbox_token: "{{ lookup('env', 'NETBOX_API_KEY') }}"
        data:
          name: "{{ manufacturer }}"
        state: "{{ install_state }}"
      loop: "{{ manufacturers }}"
      loop_control:
        loop_var: manufacturer
      tags: [ devices ]

    - name: "TASK 4: SETUP DEVICE TYPES"
      netbox.netbox.netbox_device_type:
        netbox_url: "{{ lookup('env', 'NETBOX_URL') }}"
        netbox_token: "{{ lookup('env', 'NETBOX_API_KEY') }}"
        data:
          model: "{{ device_type.model }}"
          manufacturer: "{{ device_type.manufacturer }}"
          slug: "{{ device_type.slug }}"
          part_number: "{{ device_type.part_number }}"
          u_height: 1
          is_full_depth: "{{ device_type.full_depth }}"
        state: "{{ install_state }}"
      loop: "{{ device_types }}"
      loop_control:
        loop_var: device_type
        label: "{{ device_type['model'] }}"
      tags: [ devices ]

    - name: "TASK 5: SETUP PLATFORMS"
      netbox.netbox.netbox_platform:
        netbox_url: "{{ lookup('env', 'NETBOX_URL') }}"
        netbox_token: "{{ lookup('env', 'NETBOX_API_KEY') }}"
        data:
          name: "{{ platform.name }}"
          slug: "{{ platform.slug }}"
        state: "{{ install_state }}"
      loop: "{{ platforms }}"
      loop_control:
        loop_var: platform
        label: "{{ platform['name'] }}"
      tags: [ devices ]

    - name: "TASK 6: SETUP DEVICE ROLES"
      netbox.netbox.netbox_device_role:
        netbox_url: "{{ lookup('env', 'NETBOX_URL') }}"
        netbox_token: "{{ lookup('env', 'NETBOX_API_KEY') }}"
        data:
          name: "{{ device_role.name }}"
          color: "{{ device_role.color }}"
          vm_role: "{{ device_role.vmrole }}"
        state: "{{ install_state }}"
      loop: "{{ device_roles }}"
      loop_control:
        loop_var: device_role
        label: "{{ device_role['name'] }}"
      tags: [ devices ]

    - name: "TASK 7: SETUP VLANS"
      netbox.netbox.netbox_vlan:
        netbox_url: "{{ lookup('env', 'NETBOX_URL') }}"
        netbox_token: "{{ lookup('env', 'NETBOX_API_KEY') }}"
        data:
          name: "VLAN{{ vlan.vid }}"
          vid: "{{ vlan.vid }}"
          site: "MINNESOTA01"
          description: "{{ vlan.desc }}"
        state: "{{ install_state }}"
      register: result
      loop: "{{ vlans }}"
      loop_control:
        loop_var: vlan
        label: "{{ vlan['vid'] }}"
      tags: [ ipam ]

    - name: "TASK 8: SETUP RFC1918 RIR"
      netbox.netbox.netbox_rir:
        netbox_url: "{{ lookup('env', 'NETBOX_URL') }}"
        netbox_token: "{{ lookup('env', 'NETBOX_API_KEY') }}"
        data: "{{ rir }}"
        state: "{{ install_state }}"
      loop: "{{ rirs }}"
      loop_control:
        loop_var: rir
        label: "{{ rir['name'] }}"
      tags: [ ipam ]

    - name: "TASK 8: SETUP AGGREGRATES"
      netbox.netbox.netbox_aggregate:
        netbox_url: "{{ lookup('env', 'NETBOX_URL') }}"
        netbox_token: "{{ lookup('env', 'NETBOX_API_KEY') }}"
        data:
          prefix: "{{ aggregate.name }}"
          description: "{{ aggregate.desc }}"
          rir: "{{ aggregate.rir }}"
        state: "{{ install_state }}"
      loop: "{{ aggregates }}"
      loop_control:
        loop_var: aggregate
        label: "{{ aggregate['name'] }}"
      tags: [ ipam ]

    - name: "TASK 9: SETUP PREFIXES"
      netbox.netbox.netbox_prefix:
        netbox_url: "{{ lookup('env', 'NETBOX_URL') }}"
        netbox_token: "{{ lookup('env', 'NETBOX_API_KEY') }}"
        data:
          family: 4
          prefix: "{{ prefix.prefix }}"
          site: "{{ prefix.site | default(omit) }}"
          status: "{{ prefix.status | default('Active') }}"
          description: "{{ prefix.desc }}"
          is_pool: "{{ prefix.ispool }}"
        state: "{{ install_state }}"
      loop: "{{ prefixes }}"
      loop_control:
        loop_var: prefix
        label: "{{ prefix['prefix'] }}"
      tags: [ ipam ]

    - name: "TASK 10: SETUP CIRCUIT PROVIDER"
      netbox.netbox.netbox_provider:
        netbox_url: "{{ lookup('env', 'NETBOX_URL') }}"
        netbox_token: "{{ lookup('env', 'NETBOX_API_KEY') }}"
        data: "{{ circuit_provider }}"
        state: "{{ install_state }}"
      loop: "{{ circuit_providers }}"
      loop_control:
        loop_var: circuit_provider
        label: "{{ circuit_provider['name'] }}"
      tags: [ circuit ]

    - name: Create type within Netbox with only required information
      netbox.netbox.netbox_circuit_type:
        netbox_url: "{{ lookup('env', 'NETBOX_URL') }}"
        netbox_token: "{{ lookup('env', 'NETBOX_API_KEY') }}"
        data: "{{ circuit_type }}"
        state: "{{ install_state }}"
      loop: "{{ circuit_types }}"
      loop_control:
        loop_var: circuit_type
        label: "{{ circuit_type['name'] }}"
      tags: [ circuit ]

    - name: "CREATE LOCAL CIRCUIT"
      netbox.netbox.netbox_circuit:
        netbox_url: "{{ lookup('env', 'NETBOX_URL') }}"
        netbox_token: "{{ lookup('env', 'NETBOX_API_KEY') }}"
        data: "{{ circuit }}"
        state: "{{ install_state }}"
      loop: "{{ circuits }}"
      loop_control:
        loop_var: circuit
        label: "{{ circuit['cid'] }}"
      tags: [ circuit ]

